name: setup-node-env

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - run: npm install --global yarn
      shell: bash
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: "yarn"
    - run: yarn install
      shell: bash
