import BarLoaderComponent from "./BarLoader";
import BeatLoaderComponent from "./BeatLoader";
import BounceLoaderComponent from "./BounceLoader";
import CircleLoaderComponent from "./CircleLoader";
import ClimbingBoxLoaderComponent from "./ClimbingBoxLoader";
import ClipLoaderComponent from "./ClipLoader";
import DotLoaderComponent from "./DotLoader";
import FadeLoaderComponent from "./FadeLoader";
import GridLoaderComponent from "./GridLoader";
import HashLoaderComponent from "./HashLoader";
import MoonLoaderComponent from "./MoonLoader";
import PacmanLoaderComponent from "./PacmanLoader";
import PropagateLoaderComponent from "./PropagateLoader";
import PulseLoaderComponent from "./PulseLoader";
import RingLoaderComponent from "./RingLoader";
import RiseLoaderComponent from "./RiseLoader";
import RotateLoaderComponent from "./RotateLoader";
import ScaleLoaderComponent from "./ScaleLoader";
import SyncLoaderComponent from "./SyncLoader";

import { LoaderHeightWidthProps, LoaderSizeMarginProps, LoaderSizeProps } from "./interfaces";

export const BarLoader: React.ComponentClass<LoaderHeightWidthProps> = BarLoaderComponent;
export const BeatLoader: React.ComponentClass<LoaderSizeMarginProps> = BeatLoaderComponent;
export const BounceLoader: React.ComponentClass<LoaderSizeProps> = BounceLoaderComponent;
export const CircleLoader: React.ComponentClass<LoaderSizeProps> = CircleLoaderComponent;
export const ClimbingBoxLoader: React.ComponentClass<LoaderSizeProps> = ClimbingBoxLoaderComponent;
export const ClipLoader = ClipLoaderComponent;
export const DotLoader = DotLoaderComponent;
export const FadeLoader = FadeLoaderComponent;
export const GridLoader = GridLoaderComponent;
export const HashLoader = HashLoaderComponent;
export const MoonLoader = MoonLoaderComponent;
export const PacmanLoader = PacmanLoaderComponent;
export const PropagateLoader = PropagateLoaderComponent;
export const PulseLoader = PulseLoaderComponent;
export const RingLoader = RingLoaderComponent;
export const RiseLoader = RiseLoaderComponent;
export const RotateLoader = RotateLoaderComponent;
export const ScaleLoader = ScaleLoaderComponent;
export const SyncLoader = SyncLoaderComponent;
